// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB38Fdt24nNLGuK3l-9CMlzO3MnZJLRJJI',
    appId: '1:263729019947:android:54a2a7e930a24cd7e77e6e',
    messagingSenderId: '263729019947',
    projectId: 'onigokko-16527',
    databaseURL: 'https://onigokko-16527-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'onigokko-16527.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACpxspvokJ2kXNsROyrERpPs2eEC_RqOk',
    appId: '1:263729019947:ios:2b358f5292eb470ee77e6e',
    messagingSenderId: '263729019947',
    projectId: 'onigokko-16527',
    databaseURL: 'https://onigokko-16527-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'onigokko-16527.appspot.com',
    iosBundleId: 'com.hacklab.app.onigokko.onigokko',
  );
}
